In [3]:
#question 1
import pandas as pd
data={"name":["Amber","Devansh","Sam","Ritesh"],"Age":[20,20,21,21],"Emailid":["ambersinghal98@gmail.com","devansh@gmail.com","abcd@gmail.com","pqr@ymail.com"],
     "Phone no":[9760629329,9760048612,9897648612,9853421236]}
pd.DataFrame(data)

   Age                   Emailid    Phone no     name
0   20  ambersinghal98@gmail.com  9760629329    Amber
1   20         devansh@gmail.com  9760048612  Devansh
2   21            abcd@gmail.com  9897648612      Sam
3   21             pqr@ymail.com  9853421236   Ritesh

In [39]:
#question 2
df=pd.read_csv("weather.csv")
#a
print(df.head(5))

        Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3
1  11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7
2  11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3
3  11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1
4  11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0          NW           30.0         SW      ...               29
1         ENE           39.0          E      ...               36
2          NW           85.0          N      ...               69
3          NW           54.0        WNW      ...               56
4         SSE           50.0        SSE      ...               49

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6         No
1       1012.4       1008.4         5         3     17.5     25.7        Yes
2       1009.5       1007.2         8         7     15.4     20.2        Yes
3       1005.5       1007.0         2         7     13.5     14.1        Yes
4       1018.3       1018.5         7         7     11.1     15.4        Yes

   RISK_MM  RainTomorrow
0      3.6           Yes
1      3.6           Yes
2     39.8           Yes
3      2.8           Yes
4      0.0            No

[5 rows x 24 columns]

In [40]:
#b
print(df.head(10))

         Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0   11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3
1   11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7
2   11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3
3   11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1
4   11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6
5   11/6/2007  Canberra      6.2     16.9       0.0          5.8       8.2
6   11/7/2007  Canberra      6.1     18.2       0.2          4.2       8.4
7   11/8/2007  Canberra      8.3     17.0       0.0          5.6       4.6
8   11/9/2007  Canberra      8.8     19.5       0.0          4.0       4.1
9  11/10/2007  Canberra      8.4     22.8      16.2          5.4       7.7

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0          NW           30.0         SW      ...               29
1         ENE           39.0          E      ...               36
2          NW           85.0          N      ...               69
3          NW           54.0        WNW      ...               56
4         SSE           50.0        SSE      ...               49
5          SE           44.0         SE      ...               57
6          SE           43.0         SE      ...               47
7           E           41.0         SE      ...               57
8           S           48.0          E      ...               48
9           E           31.0          S      ...               32

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6         No
1       1012.4       1008.4         5         3     17.5     25.7        Yes
2       1009.5       1007.2         8         7     15.4     20.2        Yes
3       1005.5       1007.0         2         7     13.5     14.1        Yes
4       1018.3       1018.5         7         7     11.1     15.4        Yes
5       1023.8       1021.7         7         5     10.9     14.8         No
6       1024.6       1022.2         4         6     12.4     17.3         No
7       1026.2       1024.2         6         7     12.1     15.5         No
8       1026.1       1022.7         7         7     14.1     18.9         No
9       1024.1       1020.7         7         1     13.3     21.7        Yes

   RISK_MM  RainTomorrow
0      3.6           Yes
1      3.6           Yes
2     39.8           Yes
3      2.8           Yes
4      0.0            No
5      0.2            No
6      0.0            No
7      0.0            No
8     16.2           Yes
9      0.0            No

[10 rows x 24 columns]

In [41]:
#c
print(df.mean())
print("Standard Deviation is")
print(df.std())

MinTemp             7.265574
MaxTemp            20.550273
Rainfall            1.428415
Evaporation         4.521858
Sunshine            7.909366
WindGustSpeed      39.840659
WindSpeed9am        9.651811
WindSpeed3pm       17.986339
Humidity9am        72.035519
Humidity3pm        44.519126
Pressure9am      1019.709016
Pressure3pm      1016.810383
Cloud9am            3.890710
Cloud3pm            4.024590
Temp9am            12.358470
Temp3pm            19.230874
RISK_MM             1.428415
dtype: float64
Standard Deviation is
MinTemp           6.025800
MaxTemp           6.690516
Rainfall          4.225800
Evaporation       2.669383
Sunshine          3.481517
WindGustSpeed    13.059807
WindSpeed9am      7.951929
WindSpeed3pm      8.856997
Humidity9am      13.137058
Humidity3pm      16.850947
Pressure9am       6.686212
Pressure3pm       6.469422
Cloud9am          2.956131
Cloud3pm          2.666268
Temp9am           5.630832
Temp3pm           6.640346
RISK_MM           4.225800
dtype: float64

In [42]:
#d
print(df.tail(5))

           Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
361  10/27/2008  Canberra      9.0     30.7       0.0          7.6      12.1
362  10/28/2008  Canberra      7.1     28.4       0.0         11.6      12.7
363  10/29/2008  Canberra     12.5     19.9       0.0          8.4       5.3
364  10/30/2008  Canberra     12.5     26.9       0.0          5.0       7.1
365  10/31/2008  Canberra     12.3     30.2       0.0          6.0      12.6

    WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
361         NNW           76.0        SSE      ...               15
362           N           48.0        NNW      ...               22
363         ESE           43.0        ENE      ...               47
364          NW           46.0        SSW      ...               39
365          NW           78.0         NW      ...               13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM  RainTomorrow
361         No      0.0            No
362         No      0.0            No
363         No      0.0            No
364         No      0.0            No
365         No      0.0            No

[5 rows x 24 columns]

In [38]:
#e
dd=df.iloc[0:265,2:4]
print(dd)
print(dd.mean())
print(dd.std())

     MinTemp  MaxTemp
0        8.0     24.3
1       14.0     26.9
2       13.7     23.4
3       13.3     15.5
4        7.6     16.1
5        6.2     16.9
6        6.1     18.2
7        8.3     17.0
8        8.8     19.5
9        8.4     22.8
10       9.1     25.2
11       8.5     27.3
12      10.1     27.9
13      12.1     30.9
14      10.1     31.2
15      12.4     32.1
16      13.8     31.2
17      11.7     30.0
18      12.4     32.3
19      15.6     33.4
20      15.3     33.4
21      16.4     19.4
22      12.8     18.5
23      12.0     24.3
24      15.4     28.4
25      15.6     26.9
26      13.3     22.2
27      12.9     28.0
28      15.1     24.3
29      13.6     24.1
..       ...      ...
235      0.9     12.9
236      0.8     13.0
237      4.3     12.6
238      6.3     11.8
239      3.5     14.3
240     -1.5     14.8
241      1.2     16.0
242      0.5     15.4
243      5.3     11.7
244      6.6     13.1
245     -1.6     11.5
246     -3.1     12.0
247     -0.1     14.2
248     -0.6     14.0
249      3.0     11.1
250      2.9      9.5
251     -1.3      8.8
252      1.8      8.7
253      2.9      8.4
254     -2.6     11.1
255      0.5     11.0
256      2.7     16.5
257     -1.7     13.6
258     -0.9     12.8
259     -1.8     11.5
260      1.3     10.6
261      2.4     11.6
262     -1.1     11.0
263      2.3     11.6
264     -2.2     11.6

[265 rows x 2 columns]
MinTemp     8.783396
MaxTemp    21.745660
dtype: float64
MinTemp    5.725365
MaxTemp    6.705187
dtype: float64